worked on some test scripts in t/, trying to improve testing framework

diff --git a/bin/tob b/bin/tob
--- a/bin/tob
+++ b/bin/tob
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 # tob -- thinobject 'enabler' program
 # Copyright (C) 2010 Ken Irving
 #
@@ -15,7 +14,6 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
-
 warn () {
     # synopsis: warn "ONE-LINE-PER-ARGUMENT" -> then output errmsg[] lines
     test -n "$QUIET" && return
@@ -26,7 +24,6 @@ warn () {
     }
 export -f warn
 declare -ax errmsg
-
 error () {
     # synopsis: error [-x N] OUTPUT_LINE ...
     test "$1" = -x && x=$2 && shift 2 || x=1
@@ -35,13 +32,11 @@ error () {
     exit $x
     }
 export -f error
-
 debug () {
     test -n "$DEBUG" || return
     printf "DEBUG:" >&2
     printf "\t%s\n" "$@" >&2
     }
-
 parse_query() {
     # synopsis: parse_query QUERY -> set q[], o and m indices
   # errmsg+=("$FUNCNAME($*)")
@@ -57,10 +52,9 @@ parse_query() {
   # errmsg+=("    $q" "    q[1]: ${q[1]}" "    q[2]: ${q[*]:2}")
     }
 
-
 resolve_query() { # use q[], set path, set o beyond path
   # errmsg+=("$FUNCNAME($*)")
-    unset anonymous
+    unset 'anonymous'
     resolve_path || {
         rtnval=$?
         errmsg+=("$FUNCNAME(): unable to resolve path for $q")
@@ -91,7 +85,6 @@ resolve_query() { # use q[], set path, set o beyond path
     test $o -eq $m &&
         resolve_anonymous_object
     }
-
 
 resolve_path () { # try to resolve path in query, starting at index o
   # errmsg+=("$FUNCNAME($*)")
@@ -135,7 +128,6 @@ resolve_path () { # try to resolve path in query, starting at index o
   # errmsg+=("    obj.mth: ${q[*]:o:m-o}")
   # errmsg+=("    method: ${q[*]:m}")
     }
-
 resolve_anonymous_object () { # try to resolve object type at path
   # errmsg+=("$FUNCNAME($*)")
 
@@ -158,7 +150,6 @@ resolve_anonymous_object () { # try to resolve object type at path
     method="${q[*]:m}"
     method=${method// /.}
     }
-
 resolve_named_object () { # resolve object and its type, or fail
   # errmsg+=("$FUNCNAME($*)")
     while (( o < m )); do
@@ -177,14 +168,12 @@ resolve_named_object () { # resolve object and its type, or fail
     object=${object// /.}
     return 1
     }
-
 resolve_library () {
     for lib in ${TOBLIB/:/ }; do
         test -d $lib/$1 && path=$lib/$1 && return
     done
     return 1
     }
-
 resolve_attr_search_paths () { # resolve (proto)type(s) into apaths[]
     local path target
     local type=$1 && shift
@@ -201,7 +190,7 @@ resolve_attr_search_paths () { # resolve (proto)type(s) into apaths[]
             resolve_library $type || return 1
         fi
         apaths+=($path)
-        unset type
+        unset 'type'
         for mixin in $path/{,.}^?*; do # ^Cron, .^settings, etc.
             test -L $mixin && resolve_attr_search_paths $mixin
         done
@@ -211,7 +200,6 @@ resolve_attr_search_paths () { # resolve (proto)type(s) into apaths[]
     done
     test -n "$apaths[*]" || return 1
     }
-
 resolve_search_paths () { # from (proto)type(s) to types[], apaths[], mpaths[]
     local path= target=
     shopt -s nullglob
@@ -244,7 +232,6 @@ resolve_search_paths () { # from (proto)type(s) to types[], apaths[], mpaths[]
     test -n "$apaths" || return 1
     test -n "$mpaths" || return 2
     }
-
 resolve_declaration () { 
     #   synopsis: resolve_declaration path object
     #   return 0 if declaration found and type identified
@@ -260,7 +247,6 @@ resolve_declaration () {
     return 1
     }
 
-
 cull_duplicate_paths () {
     local entry unique
     local -i i
@@ -270,9 +256,9 @@ cull_duplicate_paths () {
     for (( i=${#types[@]}-1; i>=0; i-- )); do
         entry=${types[i]}
         test "${unique/$entry/}" = "$unique" && unique+=" $entry" && continue
-        unset types[i]
-        unset envars[i]
-        unset mpaths[i]
+        unset 'types[i]'
+        unset 'envars[i]'
+        unset 'mpaths[i]'
     done
     # apaths array can include duplicates, so scan & discard, leaving last
     apaths=("${apaths[@]}") # pack array first, though...
@@ -280,49 +266,22 @@ cull_duplicate_paths () {
     for (( i=${#apaths[@]}-1; i>=0; i-- )); do
         entry=${apaths[i]}
         test "${unique/$entry/}" = "$unique" && unique+=" $entry" && continue
-        unset apaths[i]
+        unset 'apaths[i]'
     done
     }
-
 resolve_method_path () {
   # errmsg+=("$FUNCNAME($*)")
-    test "$1" = --super && super=1 && shift || unset super
+    test "$1" = --super && super=1 && shift || unset 'super'
     local method=$1
     for path in ${mpaths[@]}; do
         test -x $path/$method || continue
-        test -n "$super" && unset super && continue
+        test -n "$super" && unset 'super' && continue
         TOB_method_path=$path/$method
         return
     done
     return 1 
     }
 
-
-
-resolve_chained_methods () {
-    methods=(${1//./ })
-    test ${#methods[*]} -gt 1 || return 1
-    local m wantdirective=
-    for m in ${methods[*]}; do
-        test -n "$wantdirective" && {
-            wantdirective=
-            case $m in
-                FORK|WAIT|AND|OR|PIPE)
-                    directive+=($m)
-                    continue;;
-                *)  directive+=(WAIT);;
-            esac
-            }
-        ## fail if method does not resolve:
-        resolve_method_path $m ||
-            error -x 1 "chained method $m did not resolve"
-        chain+=($m)
-        chainpath+=($TOB_method_path)
-        wantdirective=1
-    done
-    test -n "$wantdirective" && directive+=(WAIT)
-    return 0
-    }
 
 check_chaining_directives() {
     test ${#chain[@]} = ${#directive[@]} ||
@@ -342,7 +301,6 @@ check_chaining_directives() {
             ;; 
     esac
     }
-
 parse_chain_args() {
     ## scan arguments for --tag entries to allocate args per method
     local tag=$chain
@@ -364,7 +322,30 @@ parse_chain_args() {
         ap[$tag]=$a0 &&
         ac[$tag]=$((p-a0))
     }
-
+resolve_chained_methods () {
+    methods=(${1//./ })
+    test ${#methods[*]} -gt 1 || return 1
+    local m wantdirective=
+    for m in ${methods[*]}; do
+        test -n "$wantdirective" && {
+            wantdirective=
+            case $m in
+                FORK|WAIT|AND|OR|PIPE)
+                    directive+=($m)
+                    continue;;
+                *)  directive+=(WAIT);;
+            esac
+            }
+        ## fail if method does not resolve:
+        resolve_method_path $m ||
+            error -x 131 "chained method $m did not resolve"
+        chain+=($m)
+        chainpath+=($TOB_method_path)
+        wantdirective=1
+    done
+    test -n "$wantdirective" && directive+=(WAIT)
+    return 0
+    }
 run_chained_methods () {
     declare -i i=0
     local infifo= fifo
@@ -408,21 +389,19 @@ run_chained_methods () {
     chainpid=$!
     wait $chainpid
     }
-
 TOB_resolve_method_path () {
     # synopsis: TOB_resolve_method_path [--super] METHOD -> set TOB_method_path
-    test "$1" = --super && super=1 && shift || unset super
+    test "$1" = --super && super=1 && shift || unset 'super'
     local method=$1
     for path in ${TOB_method_paths//:/ }; do
         test -x $path/$method || continue
-        test -n "$super" && unset super && continue
+        test -n "$super" && unset 'super' && continue
         TOB_method_path=$path/$method
         return
     done
     return 1
     }
 export -f TOB_resolve_method_path
-
 
 TOB_get_attr () {
     # set variable 'attr' to attribute value(s), or return false
@@ -439,7 +418,6 @@ TOB_get_attr () {
     return 1
     }
 export -f TOB_get_attr
-
 main () {
   # errmsg+=("$FUNCNAME($*)")
     while test "${1:0:1}" = -; do
@@ -485,6 +463,7 @@ main () {
         type=(${save[@]})
         }
     resolve_search_paths
+    cull_duplicate_paths
     type=(${save[@]})
 
     test -n "$types" || {
@@ -706,3 +685,4 @@ BUGS
 
 AUTHOR
     Ken.Irving@alaska.edu (c) 2007-2010
+
