commiting old work in tob components various entries using index value -1 were fixed to put a space before -1 added or worked on chained methods added VERBOSE conditional in warn()

diff --git a/bin/tob b/bin/tob
--- a/bin/tob
+++ b/bin/tob
@@ -19,7 +19,8 @@
 warn () {
     # synopsis: warn "ONE-LINE-PER-ARGUMENT" -> then output errmsg[] lines
     test -n "$QUIET" && return
-    printf "?: %s\n" "${errmsg[@]}" >&2
+    test -n "$VERBOSE" &&
+        printf "?: %s\n" "${errmsg[@]}" >&2
     errmsg=()
     printf "%s\n" "$@" >&2
     }
@@ -45,7 +46,7 @@ parse_query() {
     # synopsis: parse_query QUERY -> set q[], o and m indices
   # errmsg+=("$FUNCNAME($*)")
     test -n "$1" ||
-        error -x 13 "missing required object.method query"
+        error -x 13 "no object or method specified"
     q[0]=$1
     test ${q/./} = $q && q=..$q     # assume self object
     q[1]="${q//\///.}"             # change all / to /. for splitting
@@ -137,11 +138,19 @@ resolve_path () { # try to resolve path in query, starting at index o
 
 resolve_anonymous_object () { # try to resolve object type at path
   # errmsg+=("$FUNCNAME($*)")
-    test -L $path/^ -o -L $path/.^ || {
-        errmsg+=("no symlink found: $path/^ or $path/.^")
-        return 1
-        }
-    type=($(readlink $path/^ || readlink $path/.^))
+
+  # test -L $path/^ -o -L $path/.^ || {
+  #     errmsg+=("no symlink found: $path/^ or $path/.^")
+  #     return 1
+  #     }
+  # type=($(readlink $path/^ || readlink $path/.^))
+
+    if test -L $path/^ -o -L $path/.^; then
+        type=($(readlink $path/^ || readlink $path/.^))
+    else
+        type=Directory
+    fi
+
     cd $path ||
         error -x 2 "failed: cd $path/"
     anonymous=1
@@ -291,22 +300,53 @@ resolve_method_path () {
 
 
 resolve_chained_methods () {
-    local -a methods=(${1//./ })
-    test ${#methods[*]} -gt 1 || return 2
-    local m
+    methods=(${1//./ })
+    test ${#methods[*]} -gt 1 || return 1
+    local m wantdirective=
     for m in ${methods[*]}; do
-        resolve_method_path $m || return 1
-        chain[$m]=$TOB_method_path
-        order+=($m)
+        test -n "$wantdirective" && {
+            wantdirective=
+            case $m in
+                FORK|WAIT|AND|OR|PIPE)
+                    directive+=($m)
+                    continue;;
+                *)  directive+=(WAIT);;
+            esac
+            }
+        ## fail if method does not resolve:
+        resolve_method_path $m ||
+            error -x 1 "chained method $m did not resolve"
+        chain+=($m)
+        chainpath+=($TOB_method_path)
+        wantdirective=1
     done
+    test -n "$wantdirective" && directive+=(WAIT)
     return 0
     }
 
-run_chained_methods () {
+check_chaining_directives() {
+    test ${#chain[@]} = ${#directive[@]} ||
+        error -x 1 "mismatch chained methods and directives:"\
+            "methods: (${chain[*]})"\
+            "directives: (${directives[*]})"
+    case ${directive[@]: -1} in
+        FORK|WAIT)
+            return
+            ;;
+        AND|OR|PIPE)
+            error -x 1 "invalid last chaining directive"\
+                "methods: (${chain[*]})" \
+                "directives: (${directives[*]})"
+            ;;
+        *)  error -x 1 "invalid last chaining directive: ${directive[@]: -1}" 
+            ;; 
+    esac
+    }
+
+parse_chain_args() {
     ## scan arguments for --tag entries to allocate args per method
-    local tag=$order
+    local tag=$chain
     local -i p=1 a0=1   # p points to arg in $@, a0 is first arg for tag
-    declare -iA ap ac   # ap is arg pointer, ac is arg count for tag
     while test -n "${!p}"; do
         test ${!p} = --tag || {
             p+=1
@@ -316,30 +356,53 @@ run_chained_methods () {
             ap[$tag]=$a0 &&
             ac[$tag]=$((p-a0))
         p+=1; tag="${!p}"
+        ## should consider warning if tag does not match chain[] method...
+        ## ... or skip it...
         p+=1; a0=$p
     done
     test -n "$tag" && (( p>a0 )) && 
         ap[$tag]=$a0 &&
         ac[$tag]=$((p-a0))
+    }
 
-    ## allocate a named pipe for each pair of methods:
-    declare -a np=( "${order[@]:1}" )
-    np=(${np[@]/#//tmp/$$-})
-
-    trap "rm -f ${np[*]}" EXIT
-    for namedpipe in "${np[@]}"; do
-        mkfifo $namedpipe || error -x $? mkfifo $namedpipe failed
-    done
-
-    ## run the pipeline of methods:
-    declare -i i=0 z=${#np[@]}
-    local m
-    for m in ${order[@]}; do
-        case $i in
-            0)  ${chain[$m]} "${@:ap[$m]:ac[$m]}" > ${np[$i]} &;;
-            $z) ${chain[$m]} "${@:ap[$m]:ac[$m]}" < ${np[$i-1]} &;;
-            *)  ${chain[$m]} "${@:ap[$m]:ac[$m]}" < ${np[$i-1]} > ${np[$i]} &;;
-        esac
+run_chained_methods () {
+    declare -i i=0
+    local infifo= fifo
+    # chain[] has names, chainpath[] paths, directive[] directives
+    while test $i -lt ${#chain[@]}; do
+        if test ! -n "$infifo"; then
+            case ${directive[i]} in
+                WAIT)   "${chainpath[i]}" ;;
+                FORK)   "${chainpath[i]}" & ;;
+                AND)    "${chainpath[i]}" || exit ;;
+                OR)     "${chainpath[i]}" && exit ;;
+                PIPE)
+                    fifo=/tmp/$$-$chain
+                    while test -e $fifo; do fifo.=-$i; done
+                    trap "rm -f $fifo" EXIT
+                    mkfifo $fifo || error -x $? mkfifo $fifo failed
+                    "${chainpath[i]}" > $fifo &
+                    infifo=$fifo
+                    ;;
+                *)      error -x 1 "unknown directive: ${directive[i]}" ;;
+            esac
+        else
+            case ${directive[i]} in
+                WAIT)   "${chainpath[i]}" < $infifo ;;
+                FORK)   "${chainpath[i]}" < $infifo & ;;
+                AND)    "${chainpath[i]}" < $infifo || exit ;;
+                OR)     "${chainpath[i]}" < $infifo && exit ;;
+                PIPE)
+                    fifo=/tmp/$$-$chain
+                    while test -e $fifo; do fifo.=-$i; done
+                    trap "rm -f $fifo" EXIT
+                    mkfifo $fifo || error -x $? mkfifo $fifo failed
+                    "${chainpath[i]}" < $infifo > $fifo &
+                    infifo=$fifo
+                    ;;
+                *)      error -x 1 "unknown directive: ${directive[i]}" ;;
+            esac
+        fi
         i+=1
     done
     chainpid=$!
@@ -477,10 +540,14 @@ main () {
   # warn "CONTINUING with method $TOB_method"
 
     ## try to resolve chained methods in case method contains a dot: 
-    declare -a order
-    declare -A chain
+    declare -a chain directive chainpath
     resolve_chained_methods $TOB_method && {
-        run_chained_methods "$@"
+        check_chaining_directives
+        declare -iA ap ac   # ap is arg pointer, ac is arg count for method
+        parse_chain_args "$@"
+
+        printf "\t%s: (%s)\n" chain "${chain[*]}"  chainpath "${chainpath[*]}"  directive "${directive[*]}"
+        run_chained_methods
         exit
         }
 
