sh/tob: reworked get_type(), resolve_object(), and stuff in main()

diff --git a/sh/tob b/sh/tob
--- a/sh/tob
+++ b/sh/tob
@@ -39,7 +39,7 @@ get_type () {
     unset TOB_type
     # TODO: check xattr tob.^ for type
     type="$(stat -L -c %F $TOB_path_to_object 2> /dev/null)"
-    case "${type%% *}" in
+    case "${type%% *}" in                   # first word from stat(1) filetype
         directory)
             TOB_type=Directory
             test -L $TOB_path_to_object/^ && TOB_type=$(readlink ^)
@@ -48,87 +48,74 @@ get_type () {
             return
             ;;
         regular)   TOB_type=File;;
-        fifo)      TOB_type=NamedPipe;;
         socket)    TOB_type=Socket;;
-        character) TOB_type=CharacterSpecial;;
+        fifo)      TOB_type=NamedPipe;;
         block)     TOB_type=BlockSpecial;;
+        character) TOB_type=CharacterSpecial;;
     esac
     test -n "$TOB_type" && return 2
     test -L $arg && TOB_type=SymLink && return 3
     return 4
     }
 
-resolve_object () { # cd into object, return 2 if not a dir, return 1 on error
-    # get_type() sets TOB_type, TOB_path_to_object
+resolve_object () { 
+    #               return values 0 to 4 are from get_type()
+    #               get_type() sets TOB_type, TOB_path_to_object
+    #               return 5 if $hidden > 0 and --no-hidden was given
+    #               return 6 if unable to resolve anything
+    #
     local obspec=$1
-    local path=. # assume path is local
-    local hidden=0
+    local path=. # assume path is relative
+    hidden=0
     test ${obspec:0:1} = / && path = "" # no, path is absolute
     unset prefix
-    for elem in ${obspec//./ }; do # split on dots
-        test -n "$prefix" && elem=$prefix.$elem # failed to resolve previous
-        unset prefix
-
-        if test ${elem: -1:1} = /; then     # element is a simple directory
+    for elem in ${obspec//./ }; do          # split into elements on dots
+        test -n "$prefix" && elem=$prefix.$elem && unset prefix
+        if test ${elem: -1:1} = /; then     # element is explicitly a directory
             path+=/${elem%/}
-            continue
-
         elif test -d $path/$elem; then      # dot-terminated directory
             path+=/$elem
-            continue
-
         elif test -d $path/.$elem; then     # hidden directory
             path+=/.$elem
             hidden+=1
-            continue
-
         elif test -L $path/$elem; then      # hidden dir behind symlink?
             target=$(readlink -f $path/$elem)
             leaf=${target##*/}
             target=${target%/*}
-            test -d $target/.$leaf && {
+            if test -d $target/.$leaf; then
                 path=$target/.$leaf
-                continue
-                }
-
-        elif test -L $path/.$elem; then     # hidden dir behind dot-symlink?
+                hidden+=1
+            else
+                prefix=$elem
+            fi
+        elif test -L $path/.$elem; then     # hidden dir behind hidden symlink?
             target=$(readlink -f $path/.$elem)
             leaf=${target##*/}
             target=${target%/*}
-            test -d $target/.$leaf && {
+            if test -d $target/.$leaf; then
                 path=$target/.$leaf
-                continue
-                }
+                hidden+=1
+            else
+                prefix=$elem
+            fi
         fi
-        # failed to identify directory, so save elem to combine with next
-        prefix=$elem
     done
-
-    test $hidden -gt 0 && test -n "$NO_HIDDEN" &&
-        error --exit 105 "hidden element or elements ($hidden) in $obspec"
-
+    test $hidden -gt 0 && test -n "$NO_HIDDEN" && return 5
     test -z "$prefix" && {  # a directory object was resolved
         get_type $path
         return
         }
-
-    # if prefix remains, $path.$prefix has not been resolved as a dir-object
-    # however, a non-directory object could be there...
-
-    test -e $path/$prefix && {      # regular or special file
+    # try to resolve $path.$prefix as a regular or special file object...
+    test -e $path/$prefix && {              # regular or special file
         get_type $path/$prefix
         return
         }
-
-    test -n "$NO_HIDDEN" &&     # anything left must be hidden...
-        error --exit 107 leave element hidden in $obspec
-
-    test -e $path/.$prefix && {    # hidden regular or special file
+    test -n "$NO_HIDDEN" && return 5        # anything left must be hidden...
+    test -e $path/.$prefix && {             # hidden regular or special file
         get_type $path/.$prefix
         return
         }
-
-    test -L $path/$prefix && {      # hidden ob behind symlink?
+    test -L $path/$prefix && {              # hidden ob behind symlink?
         target=$(readlink -f $path/$prefix)
         leaf=${target##*/}
         target=${target%/*}
@@ -137,8 +124,7 @@ resolve_object () { # cd into object, return 2 if not a dir, return 1 on error
             return
             }
         }
-
-    test -L $path/.$prefix && {     # hidden ob behind dot-symlink?
+    test -L $path/.$prefix && {             # hidden ob behind dot-symlink?
         target=$(readlink -f $path/.$prefix)
         leaf=${target##*/}
         target=${target%/*}
@@ -147,6 +133,7 @@ resolve_object () { # cd into object, return 2 if not a dir, return 1 on error
             return
             }
         }
+    return 6                                # no object was resolved
     }
 
 resolve_paths () {
@@ -267,45 +254,38 @@ main () {
         case $arg in
             --method | -m)
                 method=$1 && shift
-                test $method || error --exit 111 "no method argument"
+                test $method || error --exit 101 "no method argument"
                 ;;
-        
             --arg | -a)
                 args="$args $1" && shift
                 ;;
-        
             --no-hidden | -H)
                 NO_HIDDEN=1
                 opt="$opt -H"
                 ;;
-        
             --quiet | -q)
                 QUIET=1
                 opt="$opt --quiet"
                 ;;
-        
             --verbose | -v)
                 VERBOSE=1
                 opt="$opt -v"
                 ;;
-    
             --help | -h)
                 exec awk '/^NAME$/,0' $0
                 ;;
-            
             --debug | -d)
                 DEBUG=1
                 opt="$opt -d"
                 ;;
-                
             *)
-                error --exit 112 "unsupported option $arg"
+                error --exit 102 "unsupported option $arg"
                 ;;
         esac
         arg=$1 && shift # try again...
     done
     
-    test -z "$arg" && error --exit 113 "no object specified"
+    test -z "$arg" && error --exit 103 "no object specified"
     
     test $method && { ## dispatch method from -m or --method option on objects:
         while [ $arg ]; do
@@ -315,7 +295,7 @@ main () {
                 test $VERBOSE &&
                     echo $0 $opt $arg.$method $args
                 $0 $opt $ob.$method $args ||
-                    error --exit 114 "failed in $arg.$method"
+                    error --exit 104 "failed in $arg.$method"
             fi
             arg=$1 && shift
         done
@@ -337,70 +317,53 @@ main () {
     done
 
     test -n "$TOB_object" ||
-        error --exit 116 "no object parsed from $arg with method $TOB_method"
+        error --exit 105 "no object parsed from $arg with method $TOB_method"
     
     test -n "$TOB_method" ||
-        error --exit 117 "no method parsed from $arg, object $TOB_object"
+        error --exit 106 "no method parsed from $arg, object $TOB_object"
     
-    
-    ## the next method will change directories, so store caller's location:
+    ## resolve_object() may change directories, so store caller's location:
     TOB_caller_path=$PWD
     
-    unset TOB_type
+    # resolve_object() should set TOB_type, TOB_path_to_object
     resolve_object $TOB_object
-    return_code=$?
-    
-    unset TOB_class_path
-    if test $return_code = 1; then
-        error --exit 118 failed to resolve object: $TOB_object
-    
-    elif test $return_code = 2; then
-        TOB_type=File
+    case $? in
+    1)  error --exit 111 failed to cd to $TOB_object at $TOB_path_to_object ;;
+    2)  error --exit 112 $TOB_object at $TOB_path_to_object is $TOB_type ;;
+    3)  error --exit 113 broken symlink: $TOB_object at $TOB_path_to_object ;;
+    4)  error --exit 114 no $TOB_object type at $TOB_path_to_object ;;
+    5)  error --exit 115 "hidden element or elements ($hidden) in $obspec" ;;
+    6)  test -z "$TOBLIB_NOT_OBJECT" ||
+            error --exit 116 no object resolved for $TOB_object
+        # ok to try to resolve tob library class as object
+        # first dot-delimited element must exist as a directory
+        prefix=${TOB_object%%.*}
         for toblib in $TOBLIB; do
-            test -d $toblib/File || continue
-            TOB_class_path=$toblib/File
-            break
+            test -d $toblib/$prefix/ || continue
+            exec $0 -m $TOB_method $toblib/$TOB_object
+            # to fix: the above exec call is missing args...
         done
-        warn pwd is $PWD
-        warn query object was $TOB_object
-        warn file object is $TOB_file_object
-        error --exit 119 $TOB_object resolved to a file ... how to handle it?
-    
-    elif test -n "$TOB_type"; then
-        for toblib in $TOBLIB; do
-            test -d $toblib/$TOB_type/ || continue
-            TOB_class_path=$toblib/$TOB_type
-            break
-        done
-    else
-        error --exit 124 no object type was found -- should not happen
-    fi
+        error --exit 117 failed to resolve $TOB_object under TOBLIB
+        ;;
+    esac
 
-    test -n "$TOB_class_path" ||
-        error --exit 125 type $TOB_type did not resolve to a class directory
+    ## a couple of assertion checks, probably redundant:
+    test -n "$TOB_type" ||
+        error --exit 118 failed to resolve $TOB_object type
+    test -n "$TOB_path_to_object" ||
+        error --exit 119 failed to resolve path to $TOB_object
     
-    test -n "$DEBUG" && {
+    test -n "$DEBUG" && { # all of these should now be set:
         warn DEBUG: TOB_object=$TOB_object
         warn DEBUG: TOB_method=$TOB_method
         warn DEBUG: TOB_type=$TOB_type
         warn DEBUG: TOB_path_to_object=$TOB_path_to_object
         warn DEBUG: TOB_caller_path=$TOB_caller_path
+        warn DEBUG: "args1='$args' args2='$*'"
         }
     
-    test -n $TOB_class_path || 
-        error --exit 120 no class dir resolved for $TOB_object of type $TOB_type
-    
-    test -n "$DEBUG" && {
-        warn DEBUG: TOB_path_to_object=$TOB_path_to_object
-        warn DEBUG: TOB_class_path=$TOB_class_path
-        }
-    
-    test -n "$DEBUG" &&
-        warn DEBUG: args1=\'$args\' args2=\'$*\'
-        
-
     # resolve_paths() builds arrays: types and paths, recursing on mixins
-    # - calling it with 2 args, arg2 is the resolved class path
+    # - first of 2 args is the object, not class, may include mixins
     # - types array is 1:1 with path after skipping paths[0]
     types=()
     paths=()
