bin/install-lib: add utility to install perl modules to remote host Directory.cp, Directory.file: added as symlink to system binaries sh/tob: remove code to check absolute class paths, define main() function

diff --git a/sh/tob b/sh/tob
--- a/sh/tob
+++ b/sh/tob
@@ -16,13 +16,6 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# require class handlers & methods to be under one of these paths:
-if test -n "$TOB_LIBRARY"; then
-    library=${TOB_LIBRARY//:/ } 
-else
-    library=( ~/lib/tob /usr/local/lib/tob /opt/lib/tob /usr/lib/tob /lib/tob )
-fi
-
 warn () {
     test -z "$QUIET" &&
         printf "%s\n" "$*" >&2
@@ -33,22 +26,6 @@ error () {
     test -n "$1" -a $1 == --exit && shift && exitvalue=$1 && shift
     warn "$*"
     exit $exitvalue
-    }
-
-check_classroot () {
-    # return true if class begins with allowed root
-    # return false if class does not exist or does not begin at TOB_LIBRARY
-    # variable classname is set on return if ^ or .^ is found
-    local class=$(/bin/readlink -fe $1) ||
-        error --exit 101 check failed for class $1 symlink
-    for path in ${library[@]}; do
-        test ${class#$path/} == $class || {
-            classname=${class#$path/}
-            return 0
-            }
-    done
-    error --exit 102 bad TOB_LIBRARY check or bad class in $1
-    return 1
     }
 
 resolve_object () {  # set classlink to '^', '.^', or ''; or return 1
@@ -293,202 +270,210 @@ find_default_file_class () {
     done
     }
 
-## process argument list options:
-arg=$1 && shift
-unset method
-while [ -n "$arg" -a "${arg:0:1}" == "-" ]; do # handle option ...
+main () {
 
-    if [ "$arg" == "-d" -o "$arg" == "--debug" ]; then
-        DEBUG=1
-        opt="$opt -d"
-
-    elif [ "$arg" == "-v" -o "$arg" == "--verbose" ]; then
-        VERBOSE=1
-        opt="$opt -v"
-
-    elif [ "$arg" == "-m" -o "$arg" == "--method" ]; then
-        method=$1 && shift
-        test $method || error --exit 111 "no method argument"
-
-    elif [ "$arg" == "-a" -o "$arg" == "--arg" ]; then
-        args="$args $1" && shift
-
-    elif [ "$arg" == "-H" -o "$arg" == "--no-hidden" ]; then
-        NO_HIDDEN=1
-        opt="$opt -H"
-
-    elif [ "$arg" == "-S" -o "$arg" == "--not-strict" ]; then
-        NOT_STRICT=1
-        opt="$opt -S"
-
-    elif [ "$arg" == "-q" -o "$arg" == "--quiet" ]; then
-        QUIET=1
-        opt="$opt --quiet"
-
-    elif [ "$arg" == "-h" -o "$arg" == "--help" ]; then # show manpage:
-        exec /usr/bin/awk '/^NAME$/{ok=1}ok' $0
+    ## process argument list options:
+    arg=$1 && shift
+    unset method
+    while [ -n "$arg" -a "${arg:0:1}" == "-" ]; do # handle option ...
     
-    else
-        error --exit 112 "unsupported option $arg"
-    fi
-    arg=$1 && shift # try again...
-done
-
-test -z "$arg" && error --exit 113 "no object specified"
-
-test $method && { ## dispatch method from -m or --method option on objects:
-    while [ $arg ]; do
-        if [ ${arg/=} != $arg ]; then # tag=value form detected
-            args="$args $arg"
+        if [ "$arg" == "-d" -o "$arg" == "--debug" ]; then
+            DEBUG=1
+            opt="$opt -d"
+    
+        elif [ "$arg" == "-v" -o "$arg" == "--verbose" ]; then
+            VERBOSE=1
+            opt="$opt -v"
+    
+        elif [ "$arg" == "-m" -o "$arg" == "--method" ]; then
+            method=$1 && shift
+            test $method || error --exit 111 "no method argument"
+    
+        elif [ "$arg" == "-a" -o "$arg" == "--arg" ]; then
+            args="$args $1" && shift
+    
+        elif [ "$arg" == "-H" -o "$arg" == "--no-hidden" ]; then
+            NO_HIDDEN=1
+            opt="$opt -H"
+    
+        elif [ "$arg" == "-S" -o "$arg" == "--not-strict" ]; then
+            NOT_STRICT=1
+            opt="$opt -S"
+    
+        elif [ "$arg" == "-q" -o "$arg" == "--quiet" ]; then
+            QUIET=1
+            opt="$opt --quiet"
+    
+        elif [ "$arg" == "-h" -o "$arg" == "--help" ]; then # show manpage:
+            exec /usr/bin/awk '/^NAME$/{ok=1}ok' $0
+        
         else
-            test $VERBOSE &&
-                echo $0 $opt $arg.$method $args
-            $0 $opt $ob.$method $args ||
-                error --exit 114 "failed in $arg.$method"
+            error --exit 112 "unsupported option $arg"
         fi
-        arg=$1 && shift
+        arg=$1 && shift # try again...
     done
-    exit
-    }
-
-test ${arg/.//} == $arg && # no dot found, so exec as ..method in 'self' object
-    exec $0 ..$arg "$@"
-
-## parse the method and object from the object.method specification:
-TOB_method=${arg##*.}
-TOB_object=${arg%.*}
-
-## initialize method superizer:
-super=0
-
-# if called with object.super.method, ob=object.super, so fix this...
-while test ${TOB_object%.super} != $TOB_object; do
-    TOB_object=${TOB_object%.super}
-    super=$(($super+1))
-done
-
-test -n "$TOB_object" ||
-    error --exit 116 "no object parsed from $arg with method $TOB_method"
-
-test -n "$TOB_method" ||
-    error --exit 117 "no method parsed from $arg, object $TOB_object"
-
-
-## the next method will change directories, so store caller's location:
-TOB_caller_path=$PWD
-
-resolve_and_chdir_into_object $TOB_object
-return_code=$?
-
-if test $return_code == 1; then
-    error --exit 118 failed to resolve object: $TOB_object
-
-
-elif test $return_code == 2; then
-    find_default_file_class
-    TOB_class_path=$TOB_FILE_CLASS
-    warn pwd is $PWD
-    warn query object was $TOB_object
-    warn file object is $TOB_file_object
-    error --exit 119 $TOB_object resolved to a file ... how to handle it?
-
-elif test -n "$last_classlink"; then
-  # warn object $TOB_object is a thinobject
-  # warn last_classlink is $last_classlink
-    TOB_class_path=./$classlink
-else
-  # warn object $TOB_object is a directory
-    find_default_directory_class
-    TOB_class_path=$TOB_DIRECTORY_CLASS
-fi
-
-test -n "$DEBUG" && {
-    warn DEBUG: TOB_object=$TOB_object
-    warn DEBUG: TOB_method=$TOB_method
-    warn DEBUG: TOB_path_to_object=$TOB_path_to_object
-    warn DEBUG: TOB_caller_path=$TOB_caller_path
-    }
-
-test -n $TOB_class_path || 
-    error --exit 120 no object path resolved from $TOB_object
-
-test -n "$DEBUG" && {
-    warn DEBUG: TOB_path_to_object=$TOB_path_to_object
-    warn DEBUG: TOB_class_path=$TOB_class_path
-    }
-
-test -n "$DEBUG" &&
-    warn DEBUG: args1=\'$args\' args2=\'$*\'
     
-# follow_paths() recursively builds the paths array starting with argument path
-paths=()
-follow_paths . $TOB_class_path
-# paths array now constains the full inheritance path-set, may have duplicates
-
-check_paths
-# arrays: paths, method_paths, class_names are defined (may be sparse)
-
-## export thinobject variables
-export TOB_object
-export TOB_method
-export TOB_class_path
-export TOB_caller_path
-export TOB_caller_path_to_object=$TOB_path_to_object
-
-## export thinobject utility functions
-export -f TOB_resolve_method_path
-export -f TOB_get_attr
-
-
-# create pseudo-arrays for export:
-save_IFS="$IFS"
-IFS=:
-export TOB_search_paths="${paths[*]}"
-export TOB_method_paths="${method_paths[*]}"
-export TOB_type="${class_names[*]}"
-IFS="$save_IFS"
-
-test -n "$DEBUG" && {
-    warn DEBUG: TOB_search_paths=$TOB_search_paths
-    warn DEBUG: TOB_method_paths=$TOB_method_paths
-    warn DEBUG: TOB_type=$TOB_type
-    }
-
-resolve_method_path $TOB_method &&
-    exec $TOB_method_path $args "$@"
-
-## no executable method was resolved, so try some built-ins:
-
-test $TOB_method == path && {
-    test -z "$*" && echo $TOB_path_to_object/
-    for arg in $*; do
-        test -e $arg ||
-            error --exit 121 $arg not found
-        echo $TOB_path_to_object/$arg
-    done
-    exit
-    }
-
-test "$TOB_method" == "type" &&
-    echo $TOB_type &&
+    test -z "$arg" && error --exit 113 "no object specified"
+    
+    test $method && { ## dispatch method from -m or --method option on objects:
+        while [ $arg ]; do
+            if [ ${arg/=} != $arg ]; then # tag=value form detected
+                args="$args $arg"
+            else
+                test $VERBOSE &&
+                    echo $0 $opt $arg.$method $args
+                $0 $opt $ob.$method $args ||
+                    error --exit 114 "failed in $arg.$method"
+            fi
+            arg=$1 && shift
+        done
         exit
-
-## no method was found, so check for _default method...
-
-for path in ${method_paths[@]}; do
-    ## ASSERT: class exists
-    test -e $path/_default && {
-        test -x $path/_default && {
-          # warn DEBUG thinob: exec $path/_default $TOB_object $TOB_method $*
-            exec $path/_default $TOB_method "$@"
-            }
-        ## ASSERT: _default is not executable
-        ## maybe it can contain a recipe to be executed?
-        error --exit 122 'non-executable _default "method" found'
         }
-done
+    
+    test ${arg/.//} == $arg && # no dot found, so exec as ..method in 'self' object
+        exec $0 ..$arg "$@"
+    
+    ## parse the method and object from the object.method specification:
+    TOB_method=${arg##*.}
+    TOB_object=${arg%.*}
+    
+    ## initialize method superizer:
+    super=0
+    
+    # if called with object.super.method, ob=object.super, so fix this...
+    while test ${TOB_object%.super} != $TOB_object; do
+        TOB_object=${TOB_object%.super}
+        super=$(($super+1))
+    done
+    
+    test -n "$TOB_object" ||
+        error --exit 116 "no object parsed from $arg with method $TOB_method"
+    
+    test -n "$TOB_method" ||
+        error --exit 117 "no method parsed from $arg, object $TOB_object"
+    
+    
+    ## the next method will change directories, so store caller's location:
+    TOB_caller_path=$PWD
+    
+    resolve_and_chdir_into_object $TOB_object
+    return_code=$?
+    
+    if test $return_code == 1; then
+        error --exit 118 failed to resolve object: $TOB_object
+    
+    
+    elif test $return_code == 2; then
+        find_default_file_class
+        TOB_class_path=$TOB_FILE_CLASS
+        warn pwd is $PWD
+        warn query object was $TOB_object
+        warn file object is $TOB_file_object
+        error --exit 119 $TOB_object resolved to a file ... how to handle it?
+    
+    elif test -n "$last_classlink"; then
+      # warn object $TOB_object is a thinobject
+      # warn last_classlink is $last_classlink
+        TOB_class_path=./$classlink
+    else
+      # warn object $TOB_object is a directory
+        find_default_directory_class
+        TOB_class_path=$TOB_DIRECTORY_CLASS
+    fi
+    
+    test -n "$DEBUG" && {
+        warn DEBUG: TOB_object=$TOB_object
+        warn DEBUG: TOB_method=$TOB_method
+        warn DEBUG: TOB_path_to_object=$TOB_path_to_object
+        warn DEBUG: TOB_caller_path=$TOB_caller_path
+        }
+    
+    test -n $TOB_class_path || 
+        error --exit 120 no object path resolved from $TOB_object
+    
+    test -n "$DEBUG" && {
+        warn DEBUG: TOB_path_to_object=$TOB_path_to_object
+        warn DEBUG: TOB_class_path=$TOB_class_path
+        }
+    
+    test -n "$DEBUG" &&
+        warn DEBUG: args1=\'$args\' args2=\'$*\'
+        
+    # follow_paths() recursively builds the paths array starting with argument path
+    paths=()
+    follow_paths . $TOB_class_path
+    # paths array now constains the full inheritance path-set, may have duplicates
+    
+    check_paths
+    # arrays: paths, method_paths, class_names are defined (may be sparse)
+    
+    ## export thinobject variables
+    export TOB_object
+    export TOB_method
+    export TOB_class_path
+    export TOB_caller_path
+    export TOB_caller_path_to_object=$TOB_path_to_object
+    
+    ## export thinobject utility functions
+    export -f TOB_resolve_method_path
+    export -f TOB_get_attr
+    
+    
+    # create pseudo-arrays for export:
+    save_IFS="$IFS"
+    IFS=:
+    export TOB_search_paths="${paths[*]}"
+    export TOB_method_paths="${method_paths[*]}"
+    export TOB_type="${class_names[*]}"
+    IFS="$save_IFS"
+    
+    test -n "$DEBUG" && {
+        warn DEBUG: TOB_search_paths=$TOB_search_paths
+        warn DEBUG: TOB_method_paths=$TOB_method_paths
+        warn DEBUG: TOB_type=$TOB_type
+        }
+    
+    resolve_method_path $TOB_method &&
+        exec $TOB_method_path $args "$@"
+    
+    ## no executable method was resolved, so try some built-ins:
+    
+    test $TOB_method == path && {
+        test -z "$*" && echo $TOB_path_to_object/
+        for arg in $*; do
+            test -e $arg ||
+                error --exit 121 $arg not found
+            echo $TOB_path_to_object/$arg
+        done
+        exit
+        }
+    
+    test "$TOB_method" == "type" &&
+        echo $TOB_type &&
+            exit
+    
+    ## no method was found, so check for _default method...
+    
+    for path in ${method_paths[@]}; do
+        ## ASSERT: class exists
+        test -e $path/_default && {
+            test -x $path/_default && {
+              # warn DEBUG thinob: exec $path/_default $TOB_object $TOB_method $*
+                exec $path/_default $TOB_method "$@"
+                }
+            ## ASSERT: _default is not executable
+            ## maybe it can contain a recipe to be executed?
+            error --exit 122 'non-executable _default "method" found'
+            }
+    done
+    
+    error --exit 123 "no method $TOB_method found"
+    } # end main()
 
-error --exit 123 "no method $TOB_method found"
+exit 47
+main "$@"
+
+exit 456 # should not happen
 
 ## manpage follows
 NAME
