bin/tob: reworking resolve-query and resolve-declaration for improvement

diff --git a/bin/.tob/main b/bin/.tob/main
--- a/bin/.tob/main
+++ b/bin/.tob/main
@@ -1,124 +1,68 @@
 main () {
-    test -n "$TOBLIB" || error --exit 102 "TOBLIB is not set"
+    test -n "$TOBLIB" || error -x 102 "TOBLIB is not set"
     ## process argument list options:
-    unset method
-    arg=$1 && shift
-    while test "${arg:0:1}" = -; do # handle option...
-        case $arg in
+    declare path= object= method=
+    declare -a args=() types=() mpaths=() apaths=() attr=()
+    declare -i super=0
+    qry=$1 && shift
+    while test "${qry:0:1}" = -; do # handle option...
+        case $qry in
             -q | --quiet)       QUIET=1;        opt="$opt -q" ;;
             -v | --verbose)     VERBOSE=1;      opt="$opt -v" ;;
             -d | --debug)       DEBUG=1;        opt="$opt -d" ;;
             -h | --help)        exec awk '/^NAME$/,0' $0 ;;
-            -a | --arg)         args="$args $1" && shift ;;
+            -a | --arg)         args+=($1) && shift ;;
             -m | --method)      method=$1 && shift
-                test $method || error --exit 101 "no method argument" ;;
-            *) error --exit 102 "unsupported option $arg" ;;
+                test $method || error -x 101 "no method argument" ;;
+            *) error -x 102 "unsupported option $qry" ;;
         esac
-        arg=$1 && shift # try again...
+        qry=$1 && shift # try again...
     done
     
-    test -z "$arg" && error --exit 103 "no object specified"
+    test -n "$qry" || error -x 103 "no object specified"
     
-    test $method && { ## dispatch method from -m or --method option on objects:
-        while [ $arg ]; do
-            if [ ${arg/=} != $arg ]; then # tag=value form detected
-                args="$args $arg"
-            else
-                test $VERBOSE &&
-                    echo $0 $opt $arg.$method $args
-                $0 $opt $ob.$method $args ||
-                    error --exit 104 "failed in $arg.$method"
-            fi
-            arg=$1 && shift
-        done
-        exit
-        }
-    
-    test ${arg/.//} = $arg && # no dot found, so exec as ..method in 'self' object
-        exec $0 ..$arg "$@"
-    
-    ## parse the method and object from the object.method specification:
-    TOB_method=${arg##*.}
-    TOB_object=${arg%.*}
-    
-    ## count and remove 'super' modifier(s) if at end of object:
-    declare -i super=0
-    while test "${TOB_object: -6}" = ".super"; do
-        TOB_object=${TOB_object%.super}
-        super+=1
-    done
+    test -n "$method" && method_option $qry "$@"  # ... will not return!
 
-    test -n "$TOB_object" ||
-        error --exit 105 "no object parsed from $arg with method $TOB_method"
-    
-    test -n "$TOB_method" ||
-        error --exit 106 "no method parsed from $arg, object $TOB_object"
-    
-    ## resolve_object() may change directories, so store caller's location:
-    TOB_caller_path=$PWD
+    test ${qry/.//} = $qry && # no dot found, so exec as, i.e., self.method
+        exec $0 ..$qry "$@"
 
-    test -n "$DEBUG" && { # all of these should now be set:
-        warn "DEBUG: TOB_object=$TOB_object"
-        warn "DEBUG: TOB_method=$TOB_method"
-        warn "DEBUG: super count: $super"
-        warn "DEBUG: TOB_caller_path=$TOB_caller_path"
-        warn "DEBUG: args1='$args' args2='$*'"
-        }
-    
-    declare -a types=() mpaths=() apaths=() attr=()
+    declare -x TOB_caller_path=$PWD
 
-    # resolve_object() should set TOB_type, TOB_path_to_object
-    resolve_object $TOB_object
+    # set: path, object, method, super
+
+    resolve_query $qry # will set: path, object, method, super
     return_status=$?
-  # warn "RESOLVE_OBJECT($TOB_object) returned $return_status, type $TOB_type"
-    case $return_status in
-    1)  error --exit 111 failed to cd to $TOB_object at $TOB_path_to_object ;;
-    2)  error --exit 112 $TOB_object at $TOB_path_to_object is $TOB_type ;;
-    3)  error --exit 113 broken symlink: $TOB_object at $TOB_path_to_object ;;
-    4)  error --exit 114 no $TOB_object type at $TOB_path_to_object ;;
-    6)  test -z "$TOBLIB_NOT_OBJECT" ||
-            error --exit 116 failed to resolve $TOB_object
-        # ok to try to resolve tob library class as object
-      # warn "TRY TO RESOLVE library class as object"
-        # first dot-delimited element must exist as a directory
-        prefix=${TOB_object%%.*}
-        for toblib in $TOBLIB; do
-            test -d $toblib/$prefix/ || continue
-            exec $0 $toblib/$TOB_object.$TOB_method 
-            # to fix: the above exec call is missing args...
-        done
-        error --exit 117 failed to resolve $TOB_object
-        ;;
-    esac
 
+    test -n "$DEBUG" && printf "DEBUG: %15s = %s\n" \
+        object $object      method $method \
+        super $super        type "${type[*]}" \
+        TOB_caller_path     $TOB_caller_path \
+        args1 "${args[*]}"  args2 "$*"
+   
+exit 118
+    
     ## a couple of assertion checks, probably redundant:
-    test -n "$TOB_type" ||
-        error --exit 118 failed to resolve $TOB_object type
+    test -n "$type" ||
+        error -x 118 "failed to resolve $object type"
     test -n "$TOB_path_to_object" ||
-        error --exit 119 failed to resolve path to $TOB_object
+        error -x 119 "failed to resolve path to $object"
     
     test -n "$DEBUG" && { # all of these should now be set:
-        warn "DEBUG: TOB_type=$TOB_type"
         warn "DEBUG: TOB_path_to_object=$TOB_path_to_object"
-        warn "DEBUG: calling: resolve_search_paths . $TOB_type"
+        warn "DEBUG: calling: resolve_search_paths . $type"
         }
     
     # resolve_paths() builds arrays: types and paths, recursing on mixins
     # - first of 2 args is the object, not class, may include mixins
     # - types array is 1:1 with path after skipping paths[0]
-    declare -a types=() mpaths=() apaths=()
     if test -n "${attr[*]}"; then
-        unset attr[0]   # this is TOB_type, any other entries are envars
-      # warn "CASE 1: resolve_search_paths $TOB_type"
-        resolve_search_paths $TOB_type
-      # warn "TYPES:  <${types[@]}>"
-      # warn "APATHS: <${apaths[@]}>"
-      # warn "MPATHS: <${mpaths[@]}>"
-        TOB_object=$TOB_path_to_object
+        unset attr[0]   # this is type, any other entries are envars
+        resolve_search_paths $type
+        object=$TOB_path_to_object
     else
       # warn "CASE 2"
-        unset attr[0]   # this is TOB_type, any other entries are envars
-        resolve_search_paths . $TOB_type
+        unset attr[0]   # this is type, any other entries are envars
+        resolve_search_paths . $type
     fi
 
     test -n "$DEBUG" && { # all of these should now be set:
@@ -129,8 +73,8 @@ main () {
     
     test -n "$types" || {
         test "${#apaths[@]}" -gt 1 &&
-            error --exit 120 prototype but no type resolved for $TOB_object
-        error --exit 121 no type or prototype resolved for $TOB_object
+            error -x 120 "prototype but no type resolved for $object"
+        error -x 121 "no type or prototype resolved for $object"
         }
 
     test -n "$DEBUG" && { # all of these should now be set:
@@ -141,17 +85,17 @@ main () {
     
     test "$types" || {
         test "${#apaths[@]}" -gt 1 &&
-            error --exit 120 prototype but no type resolved for $TOB_object
-        error --exit 121 no type or prototype resolved for $TOB_object
+            error -x 120 "prototype but no type resolved for $object"
+        error -x 121 "no type or prototype resolved for $object"
         }
 
     # arrays may have duplicate entries, so leave only the last such entry
     cull_duplicate_paths
     
     ## export thinobject variables
-    export TOB_object
-    export TOB_method
-    export TOB_type
+    export TOB_object=$object
+    export TOB_method=$method
+    export TOB_type=$type
     export TOB_class_path
     export TOB_caller_path
     export TOB_caller_path_to_object=$TOB_path_to_object
@@ -183,7 +127,7 @@ main () {
     done
     
     resolve_method_path $TOB_method &&
-        exec $TOB_method_path $args "$@"
+        exec $TOB_method_path "${args[@]}" "$@"
     
     ## no executable method was resolved, so try some built-ins:
     
@@ -191,7 +135,7 @@ main () {
         test -z "$*" && echo $TOB_path_to_object/
         for arg in $*; do
             test -e $arg ||
-                error --exit 121 $arg not found
+                error -x 121 "$arg not found"
             echo $TOB_path_to_object/$arg
         done
         exit
@@ -212,9 +156,9 @@ main () {
                 }
             ## ASSERT: _default exists but is not executable
             ## maybe it can contain a recipe to be executed?
-            error --exit 122 'non-executable _default "method" found'
+            error -x 122 "non-executable _default method found"
             }
     done
     
-    error --exit 123 "no method $TOB_method found"
+    error -x 123 "no method $TOB_method found"
     } # end main()
diff --git a/bin/tob b/bin/tob
--- a/bin/tob
+++ b/bin/tob
@@ -21,43 +21,13 @@ warn () {
     }
 
 error () {
-    exitvalue=1
-    test -n "$1" -a $1 = --exit && shift && exitvalue=$1 && shift
-    warn "$*"
-    exit $exitvalue
+    # synopsis: error [-x N] OUTPUT_LINE ...
+    local -i n=1
+    test "$1" = -x && n=$2 && shift 2
+    warn "$@"
+    exit $n
     }
 export -f error
-
-get_type () {
-    #               set TOB_path_to_object from arg 1
-    #               set TOB_type after analysis
-    #               cd into dir object, return 0, or 1 if cd failed 
-    #               return 2 for regular or special file
-    #               return 3 for symbolic link that does not resolve
-    #               return 4 if no type identified
-    #
-    TOB_path_to_object=$1
-    unset TOB_type
-    type="$(stat -L -c %F $TOB_path_to_object 2> /dev/null)"
-    case "${type%% *}" in                   # first word from stat(1) filetype
-        directory)
-            TOB_type=Directory
-            # TODO: check xattr tob.^ for type
-            test -L $TOB_path_to_object/.^ && TOB_type=$(readlink $TOB_path_to_object/.^)
-            test -L $TOB_path_to_object/^ && TOB_type=$(readlink $TOB_path_to_object/^)
-            cd $TOB_path_to_object 2> /dev/null || return 1
-            return
-            ;;
-        regular)   TOB_type=File;;
-        socket)    TOB_type=Socket;;
-        fifo)      TOB_type=NamedPipe;;
-        block)     TOB_type=BlockSpecial;;
-        character) TOB_type=CharacterSpecial;;
-    esac
-    test -n "$TOB_type" && return 2
-    test -L $arg && TOB_type=SymLink && return 3
-    return 4
-    }
 
 resolve_library () {
     for lib in ${TOBLIB/:/ }; do
@@ -107,148 +77,88 @@ resolve_search_paths () { # resolve (proto)type(s) into types[], apaths[], mpath
         test -L $path/^ && type=$(readlink $path/^)
         test -L $path/.^ && type=$(readlink $path/.^)
     done
-    test -n "$mpaths" || return 1
+    test -n "$apaths[*]" || return 1
+    test -n "$mpaths[*]" || return 2
     }
 
-resolve_attr_declaration () { 
-    # set TOB_type, leave envars to set in array attr; return 1 on failure
-    local path=$1
-    local ob=$2
-  # warn "PATH:<$path> OB:<$ob>"
-
-    # use TOB_search_paths or resolve class link(s) or shadow declaration:
-
-    if test -L $path/$ob -a ! -e $path/$ob; then
-        attr=($(readlink $path/$ob))
-        test ${attr:0:1} = '=' || {
-            # assume attr[0] is the type, and the declaration dot-shadows ob
-            TOB_type=$attr
-            # special fix: drop leading '.' if present in $ob:
-            TOB_path_to_object=$path/${ob#.}
-            return
-            }
-        unset attr
-    fi
-
-    if test $path = ./ -a -n "$TOB_search_paths"; then
-      # warn CASE 1
-        for p in ${TOB_search_paths/:/ }; do
-            for f in $p/$ob $p/.$ob; do
-                test -L $f -a ! -e $f || continue
-                attr=($(readlink $f))
-                test ${attr:0:1} = '=' || break 2
-                unset attr
-            done
+resolve_declaration () { 
+    #   synopsis: resolve_declaration path object
+    #   return 0 if declaration found and type identified
+    #   return 1 if no declaration found
+    local path=$1 object=$2 p
+    for p in "${apaths[@]}"; do
+        for symvar in $p/$object $p/.$object; do
+            test -L $symvar -a ! -e $symvar || continue
+            type=($(readlink $symvar))
+            test -n "$type" && test ${type:0:1} != '=' && return
         done
-
-    elif resolve_search_paths $path; then
-      # warn CASE 2
-      # warn "TYPES:  ${types[@]}"
-      # warn "APATHS: ${apaths[@]}"
-      # warn "MPATHS: ${mpaths[@]}"
-        for p in ${apaths[*]}; do
-            for f in $p/$ob $p/.$ob; do
-                test -L $f -a ! -e $f || continue
-                attr=($(readlink $f))
-                test ${attr:0:1} = '=' || break 2
-                unset attr
-            done
-        done
-
-        test -n "$attr" || test -L $path/.$ob -a ! -e $path/.$ob && {
-          # warn CASE 2b ... CHECKING: $path/.$ob
-            attr=($(readlink $path/.$ob))
-          # warn "ATTR: ${attr[@]}"
-            test ${attr:0:1} = '=' && unset attr
-          # warn "ATTR: ${attr[@]}"
-            }
-
-    elif test -L $path/.$ob -a ! -e $path/.$ob; then
-      # warn CASE 3
-        attr=($(readlink $path/.$ob))
-        test ${attr:0:1} = '=' && unset attr
-
-    fi
-
-  # warn "ATTR: ${attr[*]}"
-    test -n "${attr[*]}" || return 1
-
-    TOB_type=$attr
-    TOB_path_to_object=$path/$ob
-  # warn "TOB_type:$attr"
-  # warn "TOB_path_to_object:$path/$ob"
-    }
-
-resolve_object () { 
-    #               resolve directory or attribute object or return code 6
-    #               return values 0 to 4 are from get_type()
-    #               get_type() sets TOB_type, TOB_path_to_object
-    local obspec=$1
-  # warn OBSPEC:$obspec
-    local path=. # assume path is relative
-    test ${obspec:0:1} = / && path="" # no, path is absolute
-    unset prefix
-    for elem in ${obspec//./ }; do          # split into elements on dots
-      # warn "   ELEM:$elem"
-        test -n "$prefix" && elem=$prefix.$elem && unset prefix
-        if test ${elem: -1:1} = /; then     # element is explicitly a directory
-            path+=/${elem%/}
-          # warn "      1 $path"
-        elif test -d $path/$elem; then      # dot-terminated directory
-            path+=/$elem
-          # warn "      2 $path"
-        elif test -d $path/${elem%/*}/.${elem##*/}; then # hidden directory
-            path="$path/${elem%/*}/.${elem##*/}"
-          # warn "      3 $path"
-        elif test -d $path/.$elem; then # hidden directory
-            path="$path/.$elem"
-          # warn "      4 $path"
-        elif test -L $path/$elem; then      # hidden dir behind symlink?
-          # warn "      5 $path"
-            target="$(readlink -f $path/$elem)"
-            leaf="${target##*/}"
-            target="${target%/*}"
-            if test -d "$target/.$leaf"; then
-                path="$target/.$leaf"
-            else
-                prefix=$elem
-            fi
-        elif test -L $path/.$elem -a ! -e $path/.$elem; then # declaration?
-          # warn "      6 $path"
-            # could be .foo -> Attr/Boolean
-            # or .foo -> bar, and -d .bar/
-            # or .foo -> =123
-            # but in all these cases .foo exists as a broken symlink
-            prefix=.$elem
-        elif test -L $path/.$elem; then     # hidden dir behind hidden symlink?
-          # warn "      7 $path"
-            target=$(readlink -f $path/.$elem)
-            leaf=${target##*/}
-            target=${target%/*}
-            if test -d $target/.$leaf; then
-                path=$target/.$leaf
-            else
-                prefix=$elem
-            fi
-        else
-            prefix=$elem
-        fi
     done
-  # warn "    PATH:$path PREFIX:$prefix PWD:$PWD"
-    test -z "$prefix" && {  # a directory object was resolved
-      # warn "CALLING: get_type $path"
-        get_type $path
-        return
-        }
-    test -n "$path" || {
-      # warn "START PREFIX:<$prefix>"
-        path=${prefix%/*}
-        prefix=${prefix##/*/}
-        }
-  # warn "PATH:<$path> PREFIX:<$prefix>"
-    resolve_attr_declaration $path $prefix && return
-    return 6                                # no object was resolved
+    return 1
     }
+
+
+resolve_object () { # try to resolve path, object, type, and method from query
+  # echo "QUERY: $1"
+    local -a query=${1//\//\/.}         # substitute /. for /
+    query=(${query//./ })               # split on dot into array
+  # echo "QUERY: ${query[*]}"
+    test ${query:0:1} = / && path='' || path=.
+    local -i i p=0 n=${#query[*]}
+    for (( i=0; i<n; i+=1 )); do 
+        dir="${query[*]:i-p:p+1}"       # p previous elements + element i
+        dir=${dir// /.}                 # change "a b" to "a.b"
+        test -d $path/$dir && path+=/$dir && p=0 && continue
+        test ${dir: -1:1} = / && return 1
+        test -d $path/.$dir && path+=/.$dir && p=0 && continue
+        p+=1
+    done
+    i=n-p  # i now points to element past path portion, i.e., the object
+
+  # echo " PATH: $path"
+  # echo "    i: $i"
+
+    # existing attribute search path is useful only if path is .
+    test -n "${apaths[*]}" -a $path != . && apaths=()
+
+    test -n "${apaths[*]}" || resolve_search_paths $path || {
+        test $? -eq 1 && return 1
+        }
+
+    # work back from all-object + no-method to no-object + all-method
+    # m will start at the last query element, then decrement on each pass
+    # object is extracted from query[i] to query[m]
+    local -i m
+    for (( m=n-1; m>=i; m+=-1 )); do
+        # index m points to last element of object in query
+        object="${query[*]:i:m-i+1}"
+        object=${object// /.}
+      # echo "RESOLVE_DECLARATION $path $object ... is it an object?"
+        resolve_declaration $path $object && {
+            # success, so what is the method...?
+            method="${query[*]:m+1}"
+            method=${method// /.}
+            test -n "$method" || method=default
+          # printf "%s\t%s\n" CASE A PATH $path  TYPE "${type[*]}"  OBJECT $object  METHOD "<$method>"
+            break
+            }
+    done
+
+    return
+
+    # if $path itself is a dir object with a ^ link, we're done:
+    test -L $path/^ -o -L $path/.^ && {
+        type=$(readlink $path/^ || readlink $path/.^)
+      # echo LINK in $path for TYPE $type
+        method="${query[*]:i}"
+        method="${method// /.}"
+      # printf "%s\t%s\n" CASE B PATH $path  TYPE "$type"  METHOD $method
+        cd $path || return 2
+        TOB_path_to_object=$path
+        TOB_method=$method
+        }
+
+    }
+
 
 cull_duplicate_paths () {
     local entry
@@ -325,9 +235,11 @@ TOB_get_attr () {
     }
 
 main () {
-    test -n "$TOBLIB" || error --exit 102 "TOBLIB is not set"
+    test -n "$TOBLIB" || error -x 102 "TOBLIB is not set"
     ## process argument list options:
-    unset method
+    declare path= object= method=
+    declare -a args=() types=() mpaths=() apaths=() attr=()
+    declare -i super=0
     arg=$1 && shift
     while test "${arg:0:1}" = -; do # handle option...
         case $arg in
@@ -335,98 +247,65 @@ main () {
             -v | --verbose)     VERBOSE=1;      opt="$opt -v" ;;
             -d | --debug)       DEBUG=1;        opt="$opt -d" ;;
             -h | --help)        exec awk '/^NAME$/,0' $0 ;;
-            -a | --arg)         args="$args $1" && shift ;;
+            -a | --arg)         args+=($1) && shift ;;
             -m | --method)      method=$1 && shift
-                test $method || error --exit 101 "no method argument" ;;
-            *) error --exit 102 "unsupported option $arg" ;;
+                test $method || error -x 101 "no method argument" ;;
+            *) error -x 102 "unsupported option $arg" ;;
         esac
         arg=$1 && shift # try again...
     done
     
-    test -z "$arg" && error --exit 103 "no object specified"
+    test -n "$arg" || error -x 103 "no object specified"
     
-    test $method && { ## dispatch method from -m or --method option on objects:
-        while [ $arg ]; do
-            if [ ${arg/=} != $arg ]; then # tag=value form detected
-                args="$args $arg"
-            else
-                test $VERBOSE &&
-                    echo $0 $opt $arg.$method $args
-                $0 $opt $ob.$method $args ||
-                    error --exit 104 "failed in $arg.$method"
-            fi
-            arg=$1 && shift
-        done
-        exit
-        }
-    
-    test ${arg/.//} = $arg && # no dot found, so exec as ..method in 'self' object
+    test -n "$method" && method_option $arg "$@"  # ... will not return!
+
+    test ${arg/.//} = $arg && # no dot found, so exec as, i.e., self.method
         exec $0 ..$arg "$@"
-    
-    ## parse the method and object from the object.method specification:
-    TOB_method=${arg##*.}
-    TOB_object=${arg%.*}
-    
-    ## count and remove 'super' modifier(s) if at end of object:
-    declare -i super=0
-    while test "${TOB_object: -6}" = ".super"; do
-        TOB_object=${TOB_object%.super}
-        super+=1
-    done
 
-    test -n "$TOB_object" ||
-        error --exit 105 "no object parsed from $arg with method $TOB_method"
-    
-    test -n "$TOB_method" ||
-        error --exit 106 "no method parsed from $arg, object $TOB_object"
-    
-    ## resolve_object() may change directories, so store caller's location:
-    TOB_caller_path=$PWD
+    declare -x TOB_caller_path=$PWD
 
-    test -n "$DEBUG" && { # all of these should now be set:
-        warn "DEBUG: TOB_object=$TOB_object"
-        warn "DEBUG: TOB_method=$TOB_method"
-        warn "DEBUG: super count: $super"
-        warn "DEBUG: TOB_caller_path=$TOB_caller_path"
-        warn "DEBUG: args1='$args' args2='$*'"
-        }
-    
-    declare -a types=() mpaths=() apaths=() attr=()
+    # set: path, object, method, super
 
-    # resolve_object() should set TOB_type, TOB_path_to_object
-    resolve_object $TOB_object
+    resolve_object $arg # will set: path, object, method, super
     return_status=$?
-  # warn "RESOLVE_OBJECT($TOB_object) returned $return_status, type $TOB_type"
-    case $return_status in
-    1)  error --exit 111 failed to cd to $TOB_object at $TOB_path_to_object ;;
-    2)  error --exit 112 $TOB_object at $TOB_path_to_object is $TOB_type ;;
-    3)  error --exit 113 broken symlink: $TOB_object at $TOB_path_to_object ;;
-    4)  error --exit 114 no $TOB_object type at $TOB_path_to_object ;;
-    6)  test -z "$TOBLIB_NOT_OBJECT" ||
-            error --exit 116 failed to resolve $TOB_object
-        # ok to try to resolve tob library class as object
-      # warn "TRY TO RESOLVE library class as object"
-        # first dot-delimited element must exist as a directory
-        prefix=${TOB_object%%.*}
-        for toblib in $TOBLIB; do
-            test -d $toblib/$prefix/ || continue
-            exec $0 $toblib/$TOB_object.$TOB_method 
-            # to fix: the above exec call is missing args...
-        done
-        error --exit 117 failed to resolve $TOB_object
-        ;;
-    esac
 
+  # case $return_status in
+  # 1)  error -x 111 "failed to cd to $object at $TOB_path_to_object" ;;
+  # 2)  error -x 112 "$object at $TOB_path_to_object is $type" ;;
+  # 3)  error -x 113 "broken symlink: $object at $TOB_path_to_object" ;;
+  # 4)  error -x 114 "no $object type at $TOB_path_to_object" ;;
+  # 6)  test -z "$TOBLIB_NOT_OBJECT" ||
+  #         error -x 116 "failed to resolve $object"
+  #     # ok to try to resolve tob library class as object
+  #   # warn "TRY TO RESOLVE library class as object"
+  #     # first dot-delimited element must exist as a directory
+  #     prefix=${object%%.*}
+  #     for toblib in $TOBLIB; do
+  #         test -d $toblib/$prefix/ || continue
+  #         exec $0 $toblib/$object.$method 
+  #         # to fix: the above exec call is missing args...
+  #     done
+  #     error -x 117 "failed to resolve $object"
+  #     ;;
+  # esac
+    
+    test -n "$DEBUG" && printf "DEBUG: %15s = %s\n" \
+        object $object      method $method    super $super \
+        TOB_caller_path $TOB_caller_path \
+        args1 "${args[*]}"  args2 "$*"
+   
+exit 118
+    
     ## a couple of assertion checks, probably redundant:
-    test -n "$TOB_type" ||
-        error --exit 118 failed to resolve $TOB_object type
+    test -n "$type" ||
+        error -x 118 "failed to resolve $object type"
     test -n "$TOB_path_to_object" ||
-        error --exit 119 failed to resolve path to $TOB_object
+        error -x 119 "failed to resolve path to $object"
     
     test -n "$DEBUG" && { # all of these should now be set:
-        warn "DEBUG: TOB_type=$TOB_type"
+        warn "DEBUG: type=$type"
         warn "DEBUG: TOB_path_to_object=$TOB_path_to_object"
-        warn "DEBUG: calling: resolve_search_paths . $TOB_type"
+        warn "DEBUG: calling: resolve_search_paths . $type"
         }
     
     # resolve_paths() builds arrays: types and paths, recursing on mixins
@@ -434,17 +313,17 @@ main () {
     # - types array is 1:1 with path after skipping paths[0]
     declare -a types=() mpaths=() apaths=()
     if test -n "${attr[*]}"; then
-        unset attr[0]   # this is TOB_type, any other entries are envars
-      # warn "CASE 1: resolve_search_paths $TOB_type"
-        resolve_search_paths $TOB_type
+        unset attr[0]   # this is type, any other entries are envars
+      # warn "CASE 1: resolve_search_paths $type"
+        resolve_search_paths $type
       # warn "TYPES:  <${types[@]}>"
       # warn "APATHS: <${apaths[@]}>"
       # warn "MPATHS: <${mpaths[@]}>"
-        TOB_object=$TOB_path_to_object
+        object=$TOB_path_to_object
     else
       # warn "CASE 2"
-        unset attr[0]   # this is TOB_type, any other entries are envars
-        resolve_search_paths . $TOB_type
+        unset attr[0]   # this is type, any other entries are envars
+        resolve_search_paths . $type
     fi
 
     test -n "$DEBUG" && { # all of these should now be set:
@@ -455,8 +334,8 @@ main () {
     
     test -n "$types" || {
         test "${#apaths[@]}" -gt 1 &&
-            error --exit 120 prototype but no type resolved for $TOB_object
-        error --exit 121 no type or prototype resolved for $TOB_object
+            error -x 120 "prototype but no type resolved for $object"
+        error -x 121 "no type or prototype resolved for $object"
         }
 
     test -n "$DEBUG" && { # all of these should now be set:
@@ -467,17 +346,17 @@ main () {
     
     test "$types" || {
         test "${#apaths[@]}" -gt 1 &&
-            error --exit 120 prototype but no type resolved for $TOB_object
-        error --exit 121 no type or prototype resolved for $TOB_object
+            error -x 120 "prototype but no type resolved for $object"
+        error -x 121 "no type or prototype resolved for $object"
         }
 
     # arrays may have duplicate entries, so leave only the last such entry
     cull_duplicate_paths
     
     ## export thinobject variables
-    export TOB_object
-    export TOB_method
-    export TOB_type
+    export TOB_object=$object
+    export TOB_method=$method
+    export TOB_type=$type
     export TOB_class_path
     export TOB_caller_path
     export TOB_caller_path_to_object=$TOB_path_to_object
@@ -509,7 +388,7 @@ main () {
     done
     
     resolve_method_path $TOB_method &&
-        exec $TOB_method_path $args "$@"
+        exec $TOB_method_path "${args[@]}" "$@"
     
     ## no executable method was resolved, so try some built-ins:
     
@@ -517,7 +396,7 @@ main () {
         test -z "$*" && echo $TOB_path_to_object/
         for arg in $*; do
             test -e $arg ||
-                error --exit 121 $arg not found
+                error -x 121 "$arg not found"
             echo $TOB_path_to_object/$arg
         done
         exit
@@ -538,11 +417,11 @@ main () {
                 }
             ## ASSERT: _default exists but is not executable
             ## maybe it can contain a recipe to be executed?
-            error --exit 122 'non-executable _default "method" found'
+            error -x 122 "non-executable _default method found"
             }
     done
     
-    error --exit 123 "no method $TOB_method found"
+    error -x 123 "no method $TOB_method found"
     } # end main()
 
 main "$@"
