bin/tob: refactored resolve_query() into resolve_path() bin/tob: method_option() was factored out of main to handle tob -m M -a A options

diff --git a/bin/.tob/main b/bin/.tob/main
--- a/bin/.tob/main
+++ b/bin/.tob/main
@@ -16,27 +16,38 @@ main () {
     declare -a TOB_query=${1//\//\/.}   # change all / to /. for splitting
     query=(${query//./ })               # split on dot into array
     test ${query:0:1} = / && path='' || path=.
-    declare -i m=$((${#query[*]}-1)) o=0
+    declare -i m=$((${#query[*]}-1)) o=0 # o->prospective object, m->method
 
-    resolve_query_path ||   # set path, leave o pointing to next element
-        error -x 1 "failed to resolve path from query after $path"
+    while test ! -n "$method"; do
 
-    test $o -eq $m &&
-        resolve_anonymous_object || {
-            test $? .eq 2 && 
-                error -x 2 "failed to cd into anonymous object at path $path"
-            cd -  # restore original working dir
-            query+=(default)
-            m+=1
+        # set path, leave o pointing to next element
+        resolve_path ||
+            error -x 1 "failed to resolve path from query after $path"
+    
+        if test $o -eq $m; then
+            resolve_anonymous_object || {
+                test $? .eq 2 && 
+                    error -x 2 "failed to cd into anonymous object at path $path"
+                cd -  # restore original working dir
+                }
+    
+        test -n "$method" || {
+    
+            # assert: o<m
+        
+            # we could look for shadow objects, but that should happen with apaths
+        
+            resolve_named_object
+    
             }
+        
+        test -n "tried_default" &&
+            error -x 3 "failed to resolve object.method from query"
 
-    # assert: o<m
-
-    # we could look for shadow objects, but that should happen with apaths
-
-    resolve_named_object
-
-
+        query+=(default)
+        m+=1
+        tried_default=1
+    done 
 
 
     
