various changes to support work on method prototypes...

diff --git a/lib/Program/Shell/build-program b/lib/Program/Shell/build-program
--- a/lib/Program/Shell/build-program
+++ b/lib/Program/Shell/build-program
@@ -1,12 +1,10 @@
-#!/bin/sh
+#!/bin/bash
 
 while read line; do
     test -n "$line" -a "${line:0:2}" = "#<" && {
         f=${line#\#<}
         test -e $f && cat $f && continue
-        printf "file %s not found\n" $f
-        exit 1
-        line="#? $line"
+        printf "file %s not found\n" $f && exit 1
         }
     printf "%s\n" "$line"
 done <@template
