bin/tob: fixed resolve-named-object to set object to include path Attr/Boolean: added clear, is-true, is-false methods, change is method to assume argument 'true'

diff --git a/lib/Attr/Boolean/set b/lib/Attr/Boolean/set
--- a/lib/Attr/Boolean/set
+++ b/lib/Attr/Boolean/set
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-synopsis="Attr/Boolean.set true|false"
+synopsis="Attr/Boolean.set [true|false]"
 
 case "$1" in
 
@@ -8,11 +8,9 @@ case "$1" in
 
     false)  rm -f $TOB_object;;
 
-    "")     echo "missing required value argument" >&2
-            exit 2
-            ;;
+    "")     touch $TOB_object;;
 
-    *)      echo "invalid value: $1, must be true or false" >&2
+    *)      echo "invalid value: $1, must be true or false or missing" >&2
             exit 2
             ;;
 esac
